# action.yml
name: 'Push Propagator'
description: 'Propagates changes from one repository to another, while keeping some local changes'
inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN to be used to checkout code'
    required: true
  NEVER_OVERWRITE:
    description: 'Files that should never be overwritten, i.e. local changes should be kept'
    default: README.md src/theme.css fstab.yaml
  ALWAYS_OVERWRITE:
    description: 'Files that should always be overwritten, i.e. local changes should be discarded'
    default: src/lib-franklin.js
  BLOCKS:
    description: 'blocks that get inherited from the skeleton site'
    default:
  USER_NAME:
    description: 'User name to be used for git commit'
    required: true
  USER_EMAIL:
    description: 'User email to be used for git commit'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.NEVER_OVERWRITE }}
    - ${{ inputs.ALWAYS_OVERWRITE }}
    - ${{ inputs.BLOCKS }}
    - ${{ inputs.USER_NAME }}
    - ${{ inputs.USER_EMAIL }}